#include<stdio.h>
#include<iostream>
#include<algorithm>
#include<stdlib.h>
#include<string.h>
using namespace std;
int main()
{
    int t,n,i,j,m,k,l;
    scanf("%d",&t);
    while(t--)
    {

        char dir[20];
        scanf(" %d %s",&n,dir);
        int a[n],b[n];
        if(strcmp(dir,"left")==0)
        {
            for(i=0;i<n;i++)
            {
                k=0;
                for(j=0;j<n;j++)
                {
                    scanf("%d",&m);
                    if(m!=0)
                    {a[k]=m;
                    k++;}
                }
                j=0;
                while(j<k-1)
                {
                    if(a[j]==a[j+1])
                    {
                        a[j]=a[j]+a[j+1];
                        a[j+1]=0;
                        j++;
                    }
                    j++;
                }
                l=0;
                for(j=0;j<k;j++)
                if(a[j]!=0)
                {
                    b[l]=a[j];
                    l++;
                }
                for(j=l;j<n;j++)
                b[j]=0;
                for(j=0;j<n;j++)
                printf("%d ",b[j]);
                printf("\n");
            }

        }
        if(strcmp(dir,"right")==0)
        {
            for(i=0;i<n;i++)
            {
                k=0;
                for(j=0;j<n;j++)
                {
                    scanf("%d",&m);
                    if(m!=0)
                    {a[k]=m;
                    k++;}
                }
                j=k-1;
                while(j>=0)
                {
                    if(a[j]==a[j-1])
                    {
                        a[j]=a[j]+a[j-1];
                        a[j-1]=0;
                        j--;
                    }
                    j--;
                }
                l=n-1;
                for(j=k-1;j>=0;j--)
                if(a[j]!=0)
                {
                    b[l]=a[j];
                    l--;
                }
                for(j=l;j>=0;j--)
                b[j]=0;
                for(j=0;j<n;j++)
                printf("%d ",b[j]);
                printf("\n");
            }

        }
        if(strcmp(dir,"up")==0)
        {
            int c[n][n],d[n][n];
            for(i=0;i<n;i++)
            for(j=0;j<n;j++)
            scanf("%d",&c[i][j]);
            for(i=0;i<n;i++)
            {
                k=0;
                for(j=0;j<n;j++)
                if(c[j][i]!=0)
                {
                    a[k]=c[j][i];
                    k++;
                }
                j=0;
                while(j<k-1)
                {
                    if(a[j]==a[j+1])
                    {
                        a[j]=a[j]+a[j+1];
                        a[j+1]=0;
                        j++;
                    }
                    j++;
                }
                l=0;
                for(j=0;j<k;j++)
                if(a[j]!=0)
                {
                    b[l]=a[j];
                    l++;
                }
                for(j=l;j<n;j++)
                b[j]=0;
                for(j=0;j<n;j++)
                d[j][i]=b[j];
            }
            for(i=0;i<n;i++)
            {for(j=0;j<n;j++)
            printf("%d ",d[i][j]);
            printf("\n");}
        }
        if(strcmp(dir,"down")==0)
        {
            int c[n][n],d[n][n];
            for(i=0;i<n;i++)
            for(j=0;j<n;j++)
            scanf("%d",&c[i][j]);
            for(i=0;i<n;i++)
            {
                k=0;
                for(j=0;j<n;j++)
                if(c[j][i]!=0)
                {
                    a[k]=c[j][i];
                    k++;
                }
                j=k-1;
                while(j>=0)
                {
                    if(a[j]==a[j-1])
                    {
                        a[j]=a[j]+a[j-1];
                        a[j-1]=0;
                        j--;
                    }
                    j--;
                }
                l=n-1;
                for(j=k-1;j>=0;j--)
                if(a[j]!=0)
                {
                    b[l]=a[j];
                    l--;
                }
                for(j=l;j>=0;j--)
                b[j]=0;
                for(j=0;j<n;j++)
                d[j][i]=b[j];
            }
            for(i=0;i<n;i++)
            {for(j=0;j<n;j++)
            printf("%d ",d[i][j]);
            printf("\n");}
        }
    }

    return 0;
}
